export default {
  version: '0.2',
  language: 'en',
  enableFiletypes: ['typescript', 'javascript', 'markdown', 'json'],
  ignoreRegExpList: [
    '[а-яА-ЯёЁ]+', // Игнорируем кириллицу
  ],
  words: [
    'gramio',
    'gigachat',
    'yookassa',
    'zod',
    'eslint',
    'cspell',
    'jscpd',
    'markdownlint',
    'snappy',
    'telegram',
    'деловой',
    'дружеский',
    'юмористический',
    'продающий',
    'нейтральный',
    'эмодзи',
    'мейкеров',
    'БОТ',
    'ТОКЕН',
    'промпт',
    'промпты',
    'мультиязычный',
    'инлайн',
    'stateless',
    'btoa',
    'ngw',
    'sberbank',
    'oauth',
    'webhook',
    'powershell',
    'systemd',
    'botfather',
    'lockb',
    'деплой',
    'runtime',
    'каламбуры',
    'копирайтер',
    'маркетолог',
    'корректор',
    'timestamp',
    'PERS',
    'newbot',
  ],
  ignorePaths: ['node_modules', 'dist', 'bun.lockb', 'package-lock.json', 'yarn.lock'],
};
