import pluginUnicorn from "eslint-plugin-unicorn";
import { defineConfig } from "eslint/config";

export default defineConfig([
  pluginUnicorn.configs.all,
  {
    rules: {
      "unicorn/consistent-function-scoping": `off`,
      "unicorn/filename-case": [`error`, { case: `pascalCase` }],
      "unicorn/import-style": `off`,
      "unicorn/no-anonymous-default-export": `off`,
      "unicorn/no-array-callback-reference": `off`,
      "unicorn/no-array-reduce": `off`,
      "unicorn/no-await-expression-member": `off`,
      "unicorn/no-keyword-prefix": `off`,
      "unicorn/no-nested-ternary": `off`,
      "unicorn/no-unreadable-array-destructuring": `off`,
      "unicorn/no-useless-undefined": `off`,
      "unicorn/number-literal-case": `off`,
      "unicorn/prefer-global-this": `off`,
      "unicorn/prevent-abbreviations": [
        `error`,
        {
          allowList: {
            Arg: true,
            arg: true,
            Args: true,
            args: true,
            Dev: true,
            dev: true,
            Dir: true,
            dir: true,
            Dist: true,
            dist: true,
            Docs: true,
            docs: true,
            Env: true,
            env: true,
            Ext: true,
            ext: true,
            Fn: true,
            fn: true,
            Prop: true,
            prop: true,
            Props: true,
            props: true,
            Ref: true,
            ref: true,
            Refs: true,
            refs: true,
            Src: true,
            src: true,
            Var: true,
            var: true,
            Vars: true,
            vars: true,
          },
        },
      ],
    },
  },
  {
    files: [`**/index.*`, `**/*.{config,setup}*.{js,ts}`, `**/main.*`],
    rules: { "unicorn/filename-case": [`error`, { case: `camelCase` }] },
  },
]);
