name: Build and publish to Release
description: Checkout, install, build, zip, create GitHub Release. Outputs version (commit SHA). Uses job GITHUB_TOKEN.

outputs:
  version:
    description: Release tag (release-<sha>), used to download the artifact
    value: ${{ steps.release.outputs.version }}

runs:
  using: composite
  steps:
    - name: ðŸ“¥ Checkout
      uses: actions/checkout@v4

    - name: ðŸ° Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: ðŸ—ï¸ Install and build
      shell: bash
      run: |
        bun install --frozen-lockfile
        bun run packages/do/src/main.cli.ts build

    - name: ðŸ“¦ Zip artifact
      shell: bash
      run: zip -r dist.zip dist

    - name: ðŸ“¤ Create Release and upload artifact
      id: release
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        RELEASE_TAG: release-${{ github.sha }}
      run: |
        gh release delete "$RELEASE_TAG" --yes 2>/dev/null || true
        gh release create "$RELEASE_TAG" dist.zip \
          --repo ${{ github.repository }} \
          --title "$RELEASE_TAG" \
          --notes "Build from commit ${{ github.sha }}"
        echo "version=$RELEASE_TAG" >> $GITHUB_OUTPUT
