// cspell:disable
import type { AiModelListItem } from "./Types";

/** Curated from AiTunnel catalog; chat ids are short, routed via OpenRouter at request time. */
const items = [
  { name: `gpt-5-nano`, source: `ai-tunnel`, type: `chat` },
  { name: `gpt-5-mini`, source: `ai-tunnel`, type: `chat` },
  { name: `gpt-5`, source: `ai-tunnel`, type: `chat` },
  { name: `gpt-5-pro`, source: `ai-tunnel`, type: `chat` },
  { name: `gpt-5.4-nano`, source: `ai-tunnel`, type: `chat` },
  { name: `gpt-5.4-mini`, source: `ai-tunnel`, type: `chat` },
  { name: `gpt-5.4`, source: `ai-tunnel`, type: `chat` },
  { name: `gpt-5.4-pro`, source: `ai-tunnel`, type: `chat` },
  { name: `gpt-5.5`, source: `ai-tunnel`, type: `chat` },
  { name: `gpt-5.5-pro`, source: `ai-tunnel`, type: `chat` },
  { name: `gpt-5.2`, source: `ai-tunnel`, type: `chat` },
  { name: `gpt-5.2-pro`, source: `ai-tunnel`, type: `chat` },
  { name: `claude-sonnet-4.6`, source: `ai-tunnel`, type: `chat` },
  { name: `claude-sonnet-4.5`, source: `ai-tunnel`, type: `chat` },
  { name: `claude-opus-4.7`, source: `ai-tunnel`, type: `chat` },
  { name: `claude-opus-4.6`, source: `ai-tunnel`, type: `chat` },
  { name: `claude-opus-4.5`, source: `ai-tunnel`, type: `chat` },
  { name: `gemini-2.5-flash`, source: `ai-tunnel`, type: `chat` },
  { name: `gemini-2.5-pro`, source: `ai-tunnel`, type: `chat` },
  { name: `gemini-3-flash-preview`, source: `ai-tunnel`, type: `chat` },
  { name: `gemini-3-pro-preview`, source: `ai-tunnel`, type: `chat` },
  { name: `gemini-3.1-flash-lite`, source: `ai-tunnel`, type: `chat` },
  { name: `gemini-3.1-pro-preview`, source: `ai-tunnel`, type: `chat` },
  { name: `deepseek-v4-flash`, source: `ai-tunnel`, type: `chat` },
  { name: `deepseek-v4-pro`, source: `ai-tunnel`, type: `chat` },
  { name: `qwen3.5-plus-20260420`, source: `ai-tunnel`, type: `chat` },
  { name: `qwen3.6-flash`, source: `ai-tunnel`, type: `chat` },
  { name: `qwen3-max`, source: `ai-tunnel`, type: `chat` },
  { name: `grok-4.3`, source: `ai-tunnel`, type: `chat` },
  { name: `text-embedding-3-small`, source: `ai-tunnel`, type: `embedder` },
  { name: `text-embedding-3-large`, source: `ai-tunnel`, type: `embedder` },
  { name: `text-embedding-v4`, source: `ai-tunnel`, type: `embedder` },
  { name: `gemini-embedding-001`, source: `ai-tunnel`, type: `embedder` },
  { name: `qwen3-embedding-4b`, source: `ai-tunnel`, type: `embedder` },
  { name: `qwen3-embedding-8b`, source: `ai-tunnel`, type: `embedder` },
  { name: `codestral-embed-2505`, source: `ai-tunnel`, type: `embedder` },
  { name: `gpt-image-1-mini`, source: `ai-tunnel`, type: `image` },
  { name: `gpt-image-1`, source: `ai-tunnel`, type: `image` },
  { name: `gpt-image-1.5`, source: `ai-tunnel`, type: `image` },
  { name: `gpt-image-2`, source: `ai-tunnel`, type: `image` },
  { name: `gemini-2.5-flash-image`, source: `ai-tunnel`, type: `image` },
  { name: `gemini-3.1-flash-image-preview`, source: `ai-tunnel`, type: `image` },
  { name: `gemini-3-pro-image-preview`, source: `ai-tunnel`, type: `image` },
  { name: `flux.2-pro`, source: `ai-tunnel`, type: `image` },
  { name: `flux.2-max`, source: `ai-tunnel`, type: `image` },
  { name: `seedream-4.5`, source: `ai-tunnel`, type: `image` },
  { name: `gpt-4o-mini-transcribe`, source: `ai-tunnel`, type: `speech-recognition` },
  { name: `gpt-4o-transcribe`, source: `ai-tunnel`, type: `speech-recognition` },
] as const satisfies readonly AiModelListItem[];

export const AiModels = { items };
