// cspell:disable
/* jscpd:ignore-start */
import { Meta } from "../../common/Meta";

export const Data = Meta(
  () =>
    ({
      "meta.description": [
        ``,
        `Occasion, audience, tone, markup — ready greeting`,
        `Повод, адресат, тон, разметка — готовое поздравление`,
      ],
      "meta.title": [``, `Greeting`, `Поздравление`],
      "ui.field.addEmoji.label": [`😎`, `Emoji`, `Эмодзи`],
      "ui.field.addFormatting.label": [`📝`, `Markup`, `Разметка`],
      "ui.field.address.label": [`✉️`, `Addressing`, `Обращение`],
      "ui.field.address.option.dear_name.label": [``, `Dear + name`, `«Дорогой/ая» + имя`],
      "ui.field.address.option.formal_title.label": [``, `Formal title`, `Официально`],
      "ui.field.address.option.hi_name.label": [``, `Hi + name`, `«Привет» + имя`],
      "ui.field.address.option.no_name.label": [``, `No name`, `Без имени`],
      "ui.field.extra.label": [`📝`, `Extra context`, `Дополнительно`],
      "ui.field.extra.placeholder": [
        ``,
        `Age, date, inside joke, milestone — one short line…`,
        `Возраст, дата, шутка, контекст — одна короткая строка…`,
      ],
      "ui.field.gender.label": [`⚧️`, `Gender (addressee)`, `Пол адресата`],
      "ui.field.gender.option.female.label": [`♀️`, `Feminine`, `Женский`],
      "ui.field.gender.option.male.label": [`♂️`, `Masculine`, `Мужской`],
      "ui.field.gender.option.neutral.label": [`➗`, `Neutral`, `Нейтрально`],
      "ui.field.gender.option.unspecified.label": [`➖`, `Unspecified`, `Не указан`],
      "ui.field.hobbies.label": [`🎯`, `Interests`, `Увлечения`],
      "ui.field.hobbies.placeholder": [
        ``,
        `Hobbies, sports, fandoms — short list…`,
        `Хобби, спорт, увлечения — коротко…`,
      ],
      "ui.field.length.label": [`📏`, `Length`, `Длина`],
      "ui.field.length.option.long.label": [`📝`, `Long`, `Развёрнуто`],
      "ui.field.length.option.medium.label": [`↔️`, `Medium`, `Средне`],
      "ui.field.length.option.short.label": [`✂️`, `Short`, `Коротко`],
      "ui.field.name.label": [`✏️`, `Name`, `Имя`],
      "ui.field.name.placeholder": [``, `How to address them…`, `Как обращаться…`],
      "ui.field.occasion.label": [`🎂`, `Occasion`, `Повод`],
      "ui.field.occasion.option.birthday.label": [`🎂`, `Birthday`, `День рождения`],
      "ui.field.occasion.option.feb_23.label": [`🎖️`, `23 February`, `23 февраля`],
      "ui.field.occasion.option.march_8.label": [`🌷`, `8 March`, `8 марта`],
      "ui.field.occasion.option.new_year.label": [`🎆`, `New Year`, `Новый год`],
      "ui.field.occasion.option.newborn.label": [`👶`, `Newborn`, `Рождение ребёнка`],
      "ui.field.occasion.option.valentines.label": [`💝`, `Valentine's`, `День влюблённых`],
      "ui.field.occasion.option.wedding.label": [`💍`, `Wedding`, `Свадьба`],
      "ui.field.recipient.label": [`👤`, `For whom`, `Кому`],
      "ui.field.recipient.option.acquaintance.label": [`👋`, `Acquaintance`, `Знакомый`],
      "ui.field.recipient.option.boss.label": [`👔`, `Boss / senior`, `Руководитель`],
      "ui.field.recipient.option.brother.label": [`🧑‍🤝‍🧑`, `Brother`, `Брат`],
      "ui.field.recipient.option.colleague.label": [`💼`, `Colleague`, `Коллега`],
      "ui.field.recipient.option.dad.label": [`👨`, `Dad`, `Папа`],
      "ui.field.recipient.option.friend.label": [`🤝`, `Friend`, `Друг`],
      "ui.field.recipient.option.grandma.label": [`👵`, `Grandma`, `Бабушка`],
      "ui.field.recipient.option.grandpa.label": [`👴`, `Grandpa`, `Дедушка`],
      "ui.field.recipient.option.husband.label": [`💒`, `Husband`, `Муж`],
      "ui.field.recipient.option.loved_one.label": [`💕`, `Loved one`, `Любимый человек`],
      "ui.field.recipient.option.mom.label": [`👩`, `Mom`, `Мама`],
      "ui.field.recipient.option.sister.label": [`👭`, `Sister`, `Сестра`],
      "ui.field.recipient.option.team.label": [`👥`, `Team / group`, `Команда`],
      "ui.field.recipient.option.wife.label": [`💍`, `Wife`, `Жена`],
      "ui.field.recipient.option.young.label": [`🧒`, `Child / teen`, `Ребёнок / подросток`],
      "ui.field.rhyme.label": [`🪶`, `Rhyme`, `Рифма`],
      "ui.field.tone.label": [`🎨`, `Tone`, `Тон`],
      "ui.field.tone.option.calm.label": [`🕊️`, `Calm`, `Спокойный`],
      "ui.field.tone.option.energetic.label": [`🔥`, `Energetic`, `Бодрый`],
      "ui.field.tone.option.formal.label": [`🎩`, `Formal`, `Официальный`],
      "ui.field.tone.option.playful.label": [`😄`, `Playful`, `Игривый`],
      "ui.field.tone.option.poetic.label": [`✨`, `Poetic`, `Лиричный`],
      "ui.field.tone.option.warm.label": [`🤝`, `Warm`, `Тёплый`],
      "ui.field.writerGender.label": [`✍️`, `Writer (gender)`, `Пол (кто пишет)`],
      "ui.field.writerGender.option.female.label": [`♀️`, `Feminine`, `Женский`],
      "ui.field.writerGender.option.male.label": [`♂️`, `Masculine`, `Мужской`],
      "ui.field.writerGender.option.neutral.label": [`➗`, `Neutral`, `Нейтрально`],
      "ui.field.writerGender.option.unspecified.label": [`➖`, `Unspecified`, `Не указан`],
    }) as const,
  ({ i18n }) =>
    ({
      description: i18n(`meta.description`),
      emoji: `🎉`,
      group: `text`,
      prompt: `Write a greeting. Apply every bullet below exactly. When Name, Interests, or Extra context lines appear in the list, take names, hobbies, and facts only from those lines. Deliver the greeting text alone: continuous wishes and wording from the bullets, structured as a ready-to-send message that opens with the greeting or address from the settings.`,
      title: i18n(`meta.title`),
      uiPlan: {
        fields: [
          {
            default: `birthday`,
            id: `occasion`,
            kind: `tabs_single`,
            label: i18n(`ui.field.occasion.label`),
            options: [
              {
                label: i18n(`ui.field.occasion.option.birthday.label`),
                prompt: `Make the greeting about a birthday: wish health, joy, and a good year ahead; mention age or milestone only if Extra context provides it.`,
                value: `birthday`,
              },
              {
                label: i18n(`ui.field.occasion.option.wedding.label`),
                prompt: `Make the greeting about a wedding or engagement: love, partnership, lifelong happiness.`,
                value: `wedding`,
              },
              {
                label: i18n(`ui.field.occasion.option.newborn.label`),
                prompt: `Make the greeting about a new baby: warmth for parents and a gentle welcome for the child.`,
                value: `newborn`,
              },
              {
                label: i18n(`ui.field.occasion.option.new_year.label`),
                prompt: `Make the greeting about New Year: new beginnings, celebration, hope, and good wishes for the year ahead.`,
                value: `new_year`,
              },
              {
                label: i18n(`ui.field.occasion.option.march_8.label`),
                prompt: `Make the greeting about International Women's Day (8 March): appreciation, spring, respect, warmth.`,
                value: `march_8`,
              },
              {
                label: i18n(`ui.field.occasion.option.feb_23.label`),
                prompt: `Make the greeting about Defender of the Fatherland Day (23 February): respect, strength, and best wishes.`,
                value: `feb_23`,
              },
              {
                label: i18n(`ui.field.occasion.option.valentines.label`),
                prompt: `Make the greeting about Valentine's Day: love, partnership, tenderness.`,
                value: `valentines`,
              },
            ],
          },
          {
            default: `friend`,
            id: `recipient`,
            kind: `tabs_single`,
            label: i18n(`ui.field.recipient.label`),
            options: [
              {
                label: i18n(`ui.field.recipient.option.friend.label`),
                prompt: `Write for a close friend: warm and direct.`,
                value: `friend`,
              },
              {
                label: i18n(`ui.field.recipient.option.loved_one.label`),
                prompt: `Write for a loved one (romantic partner or beloved person): intimate, warm, sincere—like a private, heartfelt message between two people who are close.`,
                value: `loved_one`,
              },
              {
                label: i18n(`ui.field.recipient.option.mom.label`),
                prompt: `Write to your mother: layer in warmth, gratitude, and tenderness; shape address and vocabulary for a child speaking to Mom, with the closeness of that bond.`,
                value: `mom`,
              },
              {
                label: i18n(`ui.field.recipient.option.dad.label`),
                prompt: `Write to your father: blend respect, gratitude, and warmth; shape address and vocabulary for a child speaking to Dad, steady and affectionate.`,
                value: `dad`,
              },
              {
                label: i18n(`ui.field.recipient.option.grandma.label`),
                prompt: `Write to your grandmother: gentle tenderness and respect across generations; a soft family tone with room for fond memory and care.`,
                value: `grandma`,
              },
              {
                label: i18n(`ui.field.recipient.option.grandpa.label`),
                prompt: `Write to your grandfather: warm respect and affection across generations; a calm, sturdy family tone.`,
                value: `grandpa`,
              },
              {
                label: i18n(`ui.field.recipient.option.brother.label`),
                prompt: `Write to your brother: sibling warmth—direct, lively, and close; peer-to-peer tone with space for shared history and light humor where it fits.`,
                value: `brother`,
              },
              {
                label: i18n(`ui.field.recipient.option.sister.label`),
                prompt: `Write to your sister: sibling closeness—caring, open, and personal; the tone sisters share when they speak heart-to-heart.`,
                value: `sister`,
              },
              {
                label: i18n(`ui.field.recipient.option.husband.label`),
                prompt: `Write to your husband: intimate married tone—love, partnership, shared life; words that fit a spouse addressing her husband.`,
                value: `husband`,
              },
              {
                label: i18n(`ui.field.recipient.option.wife.label`),
                prompt: `Write to your wife: intimate married tone—love, tenderness, shared life; words that fit a spouse addressing his wife.`,
                value: `wife`,
              },
              {
                label: i18n(`ui.field.recipient.option.colleague.label`),
                prompt: `Write for a colleague: respectful but can be warm.`,
                value: `colleague`,
              },
              {
                label: i18n(`ui.field.recipient.option.boss.label`),
                prompt: `Write for a manager or senior person: polite and measured.`,
                value: `boss`,
              },
              {
                label: i18n(`ui.field.recipient.option.young.label`),
                prompt: `Write for a child or teenager: age-appropriate and kind.`,
                value: `young`,
              },
              {
                label: i18n(`ui.field.recipient.option.team.label`),
                prompt: `Write for a group or team: inclusive “we” tone.`,
                value: `team`,
              },
              {
                label: i18n(`ui.field.recipient.option.acquaintance.label`),
                prompt: `Write for someone you know lightly: polite and friendly, warm and respectful with a light, comfortable distance.`,
                value: `acquaintance`,
              },
            ],
          },
          {
            default: `unspecified`,
            id: `gender`,
            kind: `tabs_single`,
            label: i18n(`ui.field.gender.label`),
            options: [
              {
                label: i18n(`ui.field.gender.option.unspecified.label`),
                prompt: `Choose wording that fits the recipient; use gendered grammar where the language naturally calls for it, and keep phrasing flexible elsewhere.`,
                value: `unspecified`,
              },
              {
                label: i18n(`ui.field.gender.option.female.label`),
                prompt: `Use feminine agreement and address forms in gendered languages (e.g. Russian).`,
                value: `female`,
              },
              {
                label: i18n(`ui.field.gender.option.male.label`),
                prompt: `Use masculine agreement and address forms in gendered languages.`,
                value: `male`,
              },
              {
                label: i18n(`ui.field.gender.option.neutral.label`),
                prompt: `Use gender-neutral wording and inclusive address forms wherever the language allows; keep phrasing open and welcoming.`,
                value: `neutral`,
              },
            ],
          },
          {
            default: `unspecified`,
            id: `writerGender`,
            kind: `tabs_single`,
            label: i18n(`ui.field.writerGender.label`),
            options: [
              {
                label: i18n(`ui.field.writerGender.option.unspecified.label`),
                prompt: `Let the sender’s voice stay flexible in first person; choose natural first-person wording without locking every phrase to one gendered self-reference.`,
                value: `unspecified`,
              },
              {
                label: i18n(`ui.field.writerGender.option.female.label`),
                prompt: `Shape the greeting as from a woman writing: in gendered languages, use first-person feminine agreement whenever the writer refers to herself.`,
                value: `female`,
              },
              {
                label: i18n(`ui.field.writerGender.option.male.label`),
                prompt: `Shape the greeting as from a man writing: in gendered languages, use first-person masculine agreement whenever the writer refers to himself.`,
                value: `male`,
              },
              {
                label: i18n(`ui.field.writerGender.option.neutral.label`),
                prompt: `Use gender-neutral first-person wording for the sender where the language allows; keep the voice steady and inclusive.`,
                value: `neutral`,
              },
            ],
          },
          {
            id: `name`,
            kind: `text`,
            label: i18n(`ui.field.name.label`),
            omitWhenEmpty: true,
            placeholder: i18n(`ui.field.name.placeholder`),
            prompt: `Name: use exactly as provided; keep spelling as given.`,
          },
          {
            id: `hobbies`,
            kind: `text`,
            label: i18n(`ui.field.hobbies.label`),
            omitWhenEmpty: true,
            placeholder: i18n(`ui.field.hobbies.placeholder`),
            prompt: `Interests: when this line appears in the list, weave these hobbies or interests naturally into the text where they fit the mood and pacing.`,
          },
          {
            default: `dear_name`,
            id: `address`,
            kind: `tabs_single`,
            label: i18n(`ui.field.address.label`),
            options: [
              {
                label: i18n(`ui.field.address.option.dear_name.label`),
                prompt: `Open with “Dear [name]” using the Name field when present; align gendered words with Gender; when Name is absent, open with a warm neutral greeting that does not name the addressee.`,
                value: `dear_name`,
              },
              {
                label: i18n(`ui.field.address.option.hi_name.label`),
                prompt: `Open with “Hi [name]” when Name is present; when Name is absent, open with a short friendly greeting such as “Hi.”`,
                value: `hi_name`,
              },
              {
                label: i18n(`ui.field.address.option.no_name.label`),
                prompt: `Begin with the heart of the greeting—lead with good wishes or the main thought, and skip naming the addressee in the opening.`,
                value: `no_name`,
              },
              {
                label: i18n(`ui.field.address.option.formal_title.label`),
                prompt: `Use a formal opening suitable for official or senior contexts; align gendered forms with Gender when relevant.`,
                value: `formal_title`,
              },
            ],
          },
          {
            default: `medium`,
            id: `length`,
            kind: `tabs_single`,
            label: i18n(`ui.field.length.label`),
            options: [
              {
                label: i18n(`ui.field.length.option.short.label`),
                prompt: `Keep it brief: a few sentences.`,
                value: `short`,
              },
              {
                label: i18n(`ui.field.length.option.medium.label`),
                prompt: `Keep it medium: several sentences.`,
                value: `medium`,
              },
              {
                label: i18n(`ui.field.length.option.long.label`),
                prompt: `Make it longer: multiple sentences or short paragraphs.`,
                value: `long`,
              },
            ],
          },
          {
            default: `warm`,
            id: `tone`,
            kind: `tabs_single`,
            label: i18n(`ui.field.tone.label`),
            options: [
              {
                label: i18n(`ui.field.tone.option.warm.label`),
                prompt: `Keep the tone warm and sincere.`,
                value: `warm`,
              },
              {
                label: i18n(`ui.field.tone.option.formal.label`),
                prompt: `Keep the tone formal and polite.`,
                value: `formal`,
              },
              {
                label: i18n(`ui.field.tone.option.playful.label`),
                prompt: `Keep the tone light and playful; let humor stay gentle, good-natured, and kind toward the addressee.`,
                value: `playful`,
              },
              {
                label: i18n(`ui.field.tone.option.poetic.label`),
                prompt: `Use slightly elevated, lyrical wording—stay readable.`,
                value: `poetic`,
              },
              {
                label: i18n(`ui.field.tone.option.energetic.label`),
                prompt: `Keep the tone upbeat and energetic.`,
                value: `energetic`,
              },
              {
                label: i18n(`ui.field.tone.option.calm.label`),
                prompt: `Keep the tone gentle and calm; soft and understated, with room to breathe.`,
                value: `calm`,
              },
            ],
          },
          {
            default: true,
            id: `addEmoji`,
            kind: `toggle`,
            label: i18n(`ui.field.addEmoji.label`),
            promptOff: `Deliver the greeting as plain text: letters, numbers, standard punctuation, and spaces.`,
            promptOn: `Use emoji generously throughout the greeting: several per sentence or short stretch where they match the mood and meaning; vary them; place them to reinforce warmth or humor; spread them so each line stays easy to read, with emoji alongside the words.`,
          },
          {
            default: true,
            id: `addFormatting`,
            kind: `toggle`,
            label: i18n(`ui.field.addFormatting.label`),
            promptOff: `Plain text only; no HTML tags.`,
            promptOn: `Use <strong> or <b> HTML to stress important words and phrases—more accents than in plain text.`,
          },
          {
            default: false,
            id: `rhyme`,
            kind: `toggle`,
            label: i18n(`ui.field.rhyme.label`),
            promptOff: `Write the greeting in flowing prose; keep rhythm in the sentences and phrasing only.`,
            promptOn: `Prefer light rhyme or rhythm where it sounds natural in the language; let the rhyme support the mood and the message.`,
          },
          {
            id: `extra`,
            kind: `text`,
            label: i18n(`ui.field.extra.label`),
            omitWhenEmpty: true,
            placeholder: i18n(`ui.field.extra.placeholder`),
            prompt: `Extra context: anchor every detail you add in what this line states; build only on facts written here.`,
          },
        ],
      },
    }) as const,
);
/* jscpd:ignore-end */
