declare const __Bg: {
  readonly primary: "primary";
  readonly error: "error";
  readonly info: "info";
  readonly success: "success";
  readonly warning: "warning";
  readonly backdrop: "backdrop";
  readonly surface: "surface";
  readonly text: "text";
  readonly outline: "outline";
  readonly inverse: "inverse";
  readonly accentIndigo: "accentIndigo";
  readonly accentViolet: "accentViolet";
  readonly accentPurple: "accentPurple";
  readonly accentFuchsia: "accentFuchsia";
  readonly accentPink: "accentPink";
  readonly accentOrange: "accentOrange";
  readonly accentMagenta: "accentMagenta";
  readonly accentPlum: "accentPlum";
};
export default __Bg;
