import { defineGlobalStyles, definePreset } from "@pandacss/dev";

const globalCss = defineGlobalStyles({
  "#fog-bg": { inset: 0, pointerEvents: `none`, position: `fixed`, zIndex: -3 },
  "*": { boxSizing: `border-box` },
  ":root, [data-theme='dark']": {
    "--rgb-accent": `103 232 249`,
    "--rgb-accent-red": `252 165 165`,
  },
  "[data-theme='light']": {
    "--rgb-accent": `8 145 178`,
    "--rgb-accent-red": `220 38 38`,
  },
  "@supports (view-transition-name: none)": {
    "::view-transition-old(root), ::view-transition-new(root)": {
      animationDuration: `token(durations.fast)`,
      animationTimingFunction: `ease-out`,
    },
  },
  "[data-theme='light'] #fog-bg": { display: `none` },
  "body": {
    _before: {
      backgroundImage: `linear-gradient(token(colors.bg.grid) 1px, transparent 1px), linear-gradient(90deg, token(colors.bg.grid) 1px, transparent 1px)`,
      backgroundSize: `64px 64px`,
      content: `""`,
      inset: 0,
      pointerEvents: `none`,
      position: `fixed`,
      zIndex: -2,
    },
    bg: `bg`,
    color: `text.body`,
    fontFamily: `sans`,
    fontSize: `base`,
    lineHeight: `body`,
    margin: 0,
    minHeight: `100vh`,
    position: `relative`,
    transition: `color token(durations.fast) token(easings.default), background-color token(durations.fast) token(easings.default)`,
  },
  "html": { scrollBehavior: `smooth` },
});

export const snappyUiPreset = definePreset({
  conditions: { extend: { dark: `[data-theme="dark"] &`, light: `[data-theme="light"] &` } },
  globalCss,
  name: `@snappy/ui`,
  theme: {
    extend: {
      semanticTokens: {
        colors: {
          "accent": { value: { _light: `#0891b2`, base: `#67e8f9` } },
          "accentRed": { value: { _light: `#dc2626`, base: `#fca5a5` } },
          "status.success": { value: { _light: `#16a34a`, base: `#4ade80` } },
          "status.warning": { value: { _light: `#ca8a04`, base: `#eab308` } },
          "bg": { value: { _light: `#f5f5f7`, base: `#0a0a0c` } },
          "bg.cardBorder": { value: { _light: `rgb(0 0 0 / 8%)`, base: `rgb(255 255 255 / 12%)` } },
          "bg.cardFeatures": { value: { _light: `rgb(205 228 245 / 30%)`, base: `rgb(20 38 48 / 30%)` } },
          "bg.cardFeaturesHover": { value: { _light: `rgb(195 220 240 / 75%)`, base: `rgb(25 45 58 / 75%)` } },
          "bg.card": { value: { _light: `rgb(255 255 255 / 88%)`, base: `rgb(17 17 20 / 88%)` } },
          "bg.elevated": { value: { _light: `#fff`, base: `#111114` } },
          "bg.header": { value: { _light: `rgb(255 255 255 / 90%)`, base: `rgb(10 10 12 / 90%)` } },
          "bg.icon": { value: { _light: `rgb(0 0 0 / 4%)`, base: `rgb(255 255 255 / 6%)` } },
          "border": { value: { _light: `#e4e4e7`, base: `#35353a` } },
          "inherit": { value: { base: `inherit` } },
          "onAccent": { value: { _light: `#fff`, base: `#0a0a0c` } },
          "text.body": { value: { _light: `#27272a`, base: `#e4e4e7` } },
          "text.heading": { value: { _light: `#09090b`, base: `#fff` } },
          "text.muted": { value: { _light: `#71717a`, base: `#a1a1aa` } },
          "bg.grid": { value: { _light: `rgb(0 0 0 / 4%)`, base: `rgb(255 255 255 / 2%)` } },
          "transparent": { value: { base: `transparent` } },
        },
        shadows: {
          btn: {
            value: { _light: `0 2px 12px rgb(var(--rgb-accent) / 30%)`, base: `0 0 20px rgb(var(--rgb-accent) / 35%)` },
          },
          btnHover: {
            value: { _light: `0 4px 20px rgb(var(--rgb-accent) / 40%)`, base: `0 0 28px rgb(var(--rgb-accent) / 50%)` },
          },
          card: { value: { _light: `0 1px 3px rgb(0 0 0 / 3%)`, base: `0 1px 3px rgb(0 0 0 / 4%)` } },
          cardHover: { value: { _light: `0 4px 12px rgb(0 0 0 / 5%)`, base: `0 4px 12px rgb(0 0 0 / 6%)` } },
          focusRing: {
            value: { _light: `0 0 0 4px rgb(var(--rgb-accent) / 35%)`, base: `0 0 0 4px rgb(var(--rgb-accent) / 35%)` },
          },
        },
      },
      tokens: {
        blurs: { sm: { value: `12px` } },
        borderWidths: { thin: { value: `1px` }, medium: { value: `2px` }, accent: { value: `3px` } },
        durations: { fast: { value: `0.2s` } },
        easings: { default: { value: `ease` } },
        fonts: { inherit: { value: `inherit` }, sans: { value: `"Inter Variable", "Inter", system-ui, sans-serif` } },
        fontSizes: {
          "2xl": { value: `1.5rem` },
          "3xl": { value: `1.875rem` },
          "base": { value: `1rem` },
          "hero": { value: `clamp(2.5rem, 6vw, 4rem)` },
          "iconSm": { value: `20px` },
          "inherit": { value: `inherit` },
          "lg": { value: `1.125rem` },
          "md": { value: `1.0625rem` },
          "sm": { value: `0.875rem` },
          "xl": { value: `1.25rem` },
          "xs": { value: `0.75rem` },
        },
        fontWeights: {
          bold: { value: `700` },
          extrabold: { value: `800` },
          medium: { value: `500` },
          semibold: { value: `600` },
        },
        letterSpacings: { tight: { value: `-0.03em` }, wide: { value: `0.04em` } },
        lineHeights: { body: { value: `1.65` }, relaxed: { value: `1.6` }, tight: { value: `1.1` } },
        radii: { radius: { value: `12px` }, sm: { value: `8px` }, xs: { value: `3px` } },
        sizes: {
          "0": { value: `0` },
          "8": { value: `2rem` },
          "10": { value: `2.5rem` },
          contentNarrow: { value: `36rem` },
          contentWidth: { value: `1100px` },
          em: { value: `1em` },
          emButton: { value: `1.25em` },
          full: { value: `100%` },
          iconSm: { value: `20px` },
          minText: { value: `4.5rem` },
          strengthBar: { value: `6px` },
        },
        spacing: {
          0: { value: `0` },
          1: { value: `0.25rem` },
          2: { value: `0.5rem` },
          3: { value: `0.75rem` },
          4: { value: `1rem` },
          5: { value: `1.25rem` },
          6: { value: `1.5rem` },
          8: { value: `2rem` },
          10: { value: `2.5rem` },
          12: { value: `3rem` },
          16: { value: `4rem` },
          24: { value: `6rem` },
        },
      },
    },
  },
});
