export const CSpellConfig = {
  dictionaries: [
    `companies`,
    `misc`,
    `softwareTerms`,
    `npm`,
    `node`,
    `typescript`,
    `html`,
    `css`,
    `customWords`,
    `ru-ru`,
  ],
  dictionaryDefinitions: [{ name: `customWords`, path: `./.words.txt` }],
  enabledFileTypes: { "*": true },
  enableGlobDot: true,
  ignorePaths: [`.git`, `.vscode/**`, `**/node_modules/**`, `**/*.sql`, `bun.lockb`, `**/packages/*/src/generated/**`],
  import: `@cspell/dict-ru_ru/cspell-ext.json`,
  language: `en_US`,
  useGitignore: true,
  version: `0.2`,
};
