export const CSpellConfig = {
  dictionaries: [
    `companies`,
    `misc`,
    `softwareTerms`,
    `npm`,
    `node`,
    `typescript`,
    `html`,
    `css`,
    `customWords`,
    `ru-ru`,
  ],
  dictionaryDefinitions: [{ name: `customWords`, path: `./.words.txt` }],
  enabledFileTypes: { "*": true },
  enableGlobDot: true,
  ignorePaths: [
    `.git`,
    `.vscode/**`,
    `secrets.dev.yaml`,
    `secrets.prod.enc.yaml`,
    `secrets.prod.yaml`,
    `**/node_modules/**`,
    `**/*.sql`,
    `**/packages/*/src/generated/**`,
    `**/gradlew`,
    `**/gradlew.bat`,
    `patches`,
    `bun.lockb`,
  ],
  import: `@cspell/dict-ru_ru/cspell-ext.json`,
  language: `en_US`,
  useGitignore: true,
  version: `0.2`,
};
