name: ✅ CI

on:
  workflow_dispatch: # Только ручной запуск через GitHub UI

jobs:
  ci:
    name: ${{ matrix.task.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task:
          - name: 📦 build:site
            arg: build:site
          - name: 📦 build:app
            arg: build:app
          - name: 📦 build:ssr
            arg: build:ssr
          - name: 🧪 test
            arg: test
          - name: 📘 lint:tsc
            arg: lint:tsc
          - name: 📐 lint:eslint
            arg: lint:eslint
          - name: 💅 lint:prettier
            arg: lint:prettier
          - name: 📝 lint:cspell
            arg: lint:cspell
          - name: 🔍 lint:jscpd
            arg: lint:jscpd
          - name: 🔎 lint:knip
            arg: lint:knip
          - name: 📄 lint:markdown
            arg: lint:markdown

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🐰 Setup Bun
        uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
        with:
          bun-version: latest

      - name: 📦 Install dependencies
        run: bun install --frozen-lockfile

      - name: ▶️ Run ${{ matrix.task.name }}
        run: bun do ${{ matrix.task.arg }}
