name: 🔁 CI

on:
  workflow_dispatch:

jobs:
  ci:
    name: ${{ matrix.task.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task:
          - name: 🖥️ build:client
            arg: build:client
          - name: 🌐 build:site
            arg: build:site
          - name: ⚡ build:ssr
            arg: build:ssr
          - name: 💻 build:app
            arg: build:app
          - name: 🤖 build:app-android
            arg: build:app-android
          - name: 🧪 test
            arg: test
          - name: 📘 tsc
            arg: tsc
          - name: 🔍 eslint
            arg: eslint
          - name: ✨ prettier
            arg: prettier
          - name: 📝 cspell
            arg: cspell
          - name: 📋 jscpd
            arg: jscpd
          - name: 🧹 knip
            arg: knip
          - name: 📄 markdownlint
            arg: markdownlint

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🐰 Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: latest

      - name: 📦 Install dependencies
        run: bun install --frozen-lockfile

      - name: 🔧 Setup Android
        if: matrix.task.arg == 'build:app-android'
        uses: ./.github/actions/setup-android

      - name: ▶️ Run ${{ matrix.task.name }}
        run: bun do ${{ matrix.task.arg }}
